import os

from dotenv import load_dotenv

load_dotenv()

ZAIM_USER_ID = os.getenv("ZAIM_USER_ID")
ZAIM_PASSWORD = os.getenv("ZAIM_PASSWORD")
CHROME_DRIVER_PATH = os.getenv("CHROME_DRIVER_PATH")
SELENIUM_PATH = os.getenv("SELENIUM_PATH")
DOCKER_SELENIUM_IPADDRESS = os.getenv("DOCKER_SELENIUM_IPADDRESS")
LINE_CHANNEL_ACCESS_TOKEN = os.getenv("LINE_CHANNEL_ACCESS_TOKEN")
LINE_MESSAGE_TO_ID = os.getenv("LINE_MESSAGE_TO_ID")

ZAIM_CONSUMER_ID = os.getenv("ZAIM_CONSUMER_ID")
ZAIM_CONSUMER_SECRET = os.getenv("ZAIM_CONSUMER_SECRET")
ZAIM_ACCESS_TOKEN = os.getenv("ZAIM_ACCESS_TOKEN")
ZAIM_ACCESS_TOKEN_SECRET = os.getenv("ZAIM_ACCESS_TOKEN_SECRET")
ZAIM_OAUTH_VERIFIER = os.getenv("ZAIM_OAUTH_VERIFIER")
